name: Build and Deploy to ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_URI: 351545278583.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY_AUTH: ctse-auth
  ECR_REPOSITORY_GATEWAY: ctse-gateway
  ECS_CLUSTER: ctse-microservice-cluster
  ECS_SERVICE_AUTH: ctse-auth-service
  ECS_SERVICE_GATEWAY: ctse-gateway-service
  TASK_DEF_AUTH: ecs/auth-task-def.json
  TASK_DEF_GATEWAY: ecs/gateway-task-def.json
  MONGO_URI: ${{ secrets.MONGO_URI }}
  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
  REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: sonarcloud
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push auth image
        run: |
          docker build -t $ECR_URI/$ECR_REPOSITORY_AUTH:latest ./auth-microservice
          docker push $ECR_URI/$ECR_REPOSITORY_AUTH:latest

      - name: Build, tag, and push gateway image
        run: |
          docker build -t $ECR_URI/$ECR_REPOSITORY_GATEWAY:latest ./api-gateway
          docker push $ECR_URI/$ECR_REPOSITORY_GATEWAY:latest

      - name: Inject secrets into auth task def
        run: |
          envsubst < $TASK_DEF_AUTH > ecs/auth-task-def-processed.json

      - name: Inject secrets into gateway task def
        run: |
          envsubst < $TASK_DEF_GATEWAY > ecs/gateway-task-def-processed.json

      - name: Register new auth task definition
        id: register-auth
        uses: aws-actions/amazon-ecs-register-task-definition@v1
        with:
          task-definition: ecs/auth-task-def-processed.json

      - name: Register new gateway task definition
        id: register-gateway
        uses: aws-actions/amazon-ecs-register-task-definition@v1
        with:
          task-definition: ecs/gateway-task-def-processed.json

      - name: Deploy to auth ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          service: ${{ env.ECS_SERVICE_AUTH }}
          cluster: ${{ env.ECS_CLUSTER }}
          task-definition: ${{ steps.register-auth.outputs.task-definition-arn }}
          wait-for-service-stability: true

      - name: Deploy to gateway ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          service: ${{ env.ECS_SERVICE_GATEWAY }}
          cluster: ${{ env.ECS_CLUSTER }}
          task-definition: ${{ steps.register-gateway.outputs.task-definition-arn }}
          wait-for-service-stability: true
